[build]
  base = "web"
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"

[functions."daily-reset"]
  schedule = "0 0 * * *"

[functions."signals-worker"]
  schedule = "*/2 * * * *" # executa a cada 2 minutos

[[edge_functions]]
  function = "events"
  path = "/events"

[dev]
  command = "npm run dev"
  port = 5173
  targetPort = 5173